---
name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: component version
        required: true
      mirror:
        description: tiup mirror url
        required: true
      git-ref:
        description: git ref
        required: true

jobs:
  release:
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        platform:
          - "ubuntu-18.04"
          - "macOS-latest"
        os:
          - "linux"
          - "darwin"
        arch:
          - "amd64"
          - "arm64"
        exclude:
          - platform: ubuntu-18.04
            os: "darwin"
          - platform: macOS-latest
            os: "linux"
    runs-on: ${{ matrix.platform }}
    env:
      working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git-ref }}
          path: go/src/github.com/${{ github.repository }}
          fetch-depth: 0

      - name: install toolchains
        id: install_toolchains
        run: |
          if [ `uname` = "Linux" ]; then
            sudo apt-get update && sudo apt-get -qy install gcc-aarch64-linux-gnu
          fi
          echo "install_toolchains success."

      - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
        id: build_insight
        working-directory: ${{ env.working-directory }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          export GOPATH=${GITHUB_WORKSPACE}/go
          export PATH=$PATH:$GOPATH/bin
          export CGO_ENABLED=1 
          if [ "$GOARCH" = "arm64" ]; then
            export CC=aarch64-linux-gnu-gcc
          fi
          if [ "$GOOS" = "darwin" ]; then
            export CC=clang
          fi

          BUILD_FLAGS='-trimpath' make -C collector static && \
          echo "Build success."

      - name: Package components
        id: packaging
        working-directory: ${{ env.working-directory }}
        env:
          ARCH: ${{ matrix.os }}-${{ matrix.arch }}
          REL_VER: ${{ github.event.inputs.version }}
        run: |
          TMP_DIR=`mktemp -d`
          export TIUP_HOME="$TMP_DIR/home"
          echo ::set-output name=TIUP_HOME::$TIUP_HOME
          echo ::set-output name=TIUP_BIN::$TIUP_HOME/bin/tiup

          rm -rf $TIUP_HOME && mkdir -p $TIUP_HOME/{bin,keys}
          wget -O $TMP_DIR/tiup-linux-amd64.tar.gz -q https://tiup-mirrors.pingcap.com/tiup-linux-amd64.tar.gz
          tar -zxf $TMP_DIR/tiup-linux-amd64.tar.gz -C $TIUP_HOME/bin && chmod 755 $TIUP_HOME/bin/tiup
          curl -s https://tiup-mirrors.pingcap.com/root.json -o $TIUP_HOME/bin/root.json

          mkdir -p package

          # download prebuilt fio binary
          export FIO_VER=fio-3.8.${ARCH}
          wget https://download.pingcap.org/${FIO_VER}.tar.gz
          tar zxvf ${FIO_VER}.tar.gz
          mv ${FIO_VER}/fio bin/

          # make tar reproducible
          export COMMIT_TIMESTAMP=`git show --no-patch --no-notes --pretty='%aI'`
          TAR="tar --sort=name --mtime=${{ steps.get_git.outputs.COMMIT_TIMESTAMP }} --owner=0 --group=0 --numeric-owner"

          # package component
          ${TAR} -C bin -czf package/insight-${REL_VER}-${ARCH}.tar.gz insight fio

     
